version: '3.8'

services:
  # Servidor UNAP (para producción en la nube)
  unap-server:
    build: .
    container_name: unap-server-prod
    ports:
      - "80:5000"  # Puerto 80 para HTTP público
    environment:
      - PROCESS_ID=0
      - PROCESS_NAME=UNAP-Server-Production
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - lamport-network
    command: python server.py

  # Nginx para proxy reverso y SSL (opcional)
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"  # HTTPS
      - "80:80"    # HTTP redirect
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Certificados SSL
    depends_on:
      - unap-server
    restart: unless-stopped
    networks:
      - lamport-network

networks:
  lamport-network:
    driver: bridge 